config/routes.rb
BookmarksApp::Application.routes.draw do

  resources :users

  root              to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  # callback safety
  before_save { self.email.downcase! }

  # name validation
  validates :name, presence: true, length: { maximum: 50 }

  # email validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }

  # password validation
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  # def feedback
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  end
  def create
  	@user = User.new(params[:user])
  	if @user.save
      flash[:success] = "welcome to bookmark-app"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# return title based on input string
	def full_title page_title
		base_title = "bookmark-app"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, size = 50 )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer well well-large">
	<small>
		&copy; <%= Time.now.year %> Whales
	</small>
	<nav>
		<ul>
			<li><i class="icon-envelope"></i> <%= link_to "contact", 
			contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "bookmark-app", root_path, id: "logo", class: "brand" %>
			<nav>
				<ul class="nav pull-left">
					<li>
						<form class="navbar-search pull-left">
  						<input type="text" class="search-query"
  						placeholder="titles, tags, descriptions">
						</form>
					</li>
				</ul>
				<ul class="nav pull-right">		
					<li><%= link_to "home", root_path %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to "help", help_path %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to "sign.in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title (yield :title) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'contact') %>
<div class="">
	<h1>Whales team</h1>
	<h2>Szymon Blaszczynski</h2>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'help') %>
<div class="">
	<h1>help</h1>
	<h2>Will guide you through steps required to bookmark your stuff.</h2>
</div>

app/views/static_pages/home.html.erb
<div class="center">
	<h1>host.bookmarks in one place</h1>

	<h2>... soon.will be full of bookmarks ...</h2>

	<p>Oh, yes you can store bookmarks, lookup, copy bookmarks 
	of others or keep them private, so nobody else can see them.</p>

	<%= link_to "sign.up soon", signup_path, 
		class: "btn btn-large btn-primary", id: "signup_button" %>
	<br><br>
	<form class="form-search">
    <input type="text" class="span6 search-query" placeholder="search through bookmarks">
    <button type="submit" class="btn"><i class="icon-search"></i> search</button>
	</form>
	<table class="table table-hover">
		<tr>
				<td></td><td class="span3"><strong>title</strong></td><td class="span4"><strong>tags<strong></td>
				<td class="span5"><strong>description<strong></td>
		</tr>
		<tr>
			<td><i class="icon-share"></i><td>9gag</td><td>addictive fun more fun</td>
			<td>don't you even go there ;)</td>
		</tr>
		<tr>
			<td><i class="icon-share"></i><td>bookmark-app</td><td>the next best thing</td><td>you will see</td>
		</tr>
	</table>
	<div class="pagination">
	  <ul>
	    <li><a href="#"><i class="icon-chevron-left"></i> Prev</a></li>
	    <li><a href="#">1</a></li>
	    <li><a href="#">2</a></li>
	    <li><a href="#">3</a></li>
	    <li><a href="#">4</a></li>
	    <li><a href="#">5</a></li>
	    <li><a href="#">Next <i class="icon-chevron-right"></i></a></li>
	  </ul>
	</div>
</div>
<!--
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
-->

app/views/users/new.html.erb
<% provide(:title, 'sign.up') %>
<h1>sign.up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label :name, "name" %>
			<%= f.text_field :name %>
			<%= f.label :email, "email" %>
			<%= f.text_field :email %>
			<%= f.label :password, "password" %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation, "confirm" %>
			<%= f.password_field :password_confirmation %>
			<%= f.submit "create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name + " profile") %>
<div class="">
	<div class="row">
		<aside class="span4">
			<section>
				<h1>
					<%=	gravatar_for @user, 66 %>
					<%= @user.name %>
				</h1>
			</section>
		</aside>
	</div>
</div>